import { Roboto } from "next/font/google";
// import { SessionProvider } from "next-auth/react";
import type { Metadata } from "next";
import Navbar from "@/components/sections/navbar/Navbar";
import Footer from "@/components/sections/footer/Footer";
import NavWrapper from "@/components/sections/navbar/NavWrapper";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased max-w-screen-2xl mx-auto`}
      >
        {/* <SessionProvider> */}
        <div className="min-h-svh flex flex-col">
          <NavWrapper>
            <Navbar />
          </NavWrapper>
          {children}
          <Footer />
        </div>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
